const express = require('express');
const path = require('path');
const app = express();
app.get('/', (req, res) => res.sendFile(__dirname + path.sep + 'index.html'));
app.use('/static', express.static('./static'));
app.use('/cashier', express.static('./cashier'));
app.use('/kitchen', express.static('./kitchen'));
app.use('/business', express.static('./business'));
app.use('/menu', express.static('./menu'));
app.listen(8200, () => console.log('Listening on port 8200'));
