const STATUS_ORDERING = 1;
const STATUS_PREPARING = 2;
const STATUS_READY = 3;
const STATUS_CANCELLED = 4;
const STATUS_AT_TABLE = 5;
const STATUS_PICKED_IP = 6;

exports.STATUS_ORDERING = STATUS_ORDERING;
exports.STATUS_PREPARING = STATUS_PREPARING;
exports.STATUS_READY = STATUS_READY;
exports.STATUS_CANCELLED = STATUS_CANCELLED;
exports.STATUS_AT_TABLE = STATUS_AT_TABLE;
exports.STATUS_PICKED_IP = STATUS_PICKED_IP;